default:
   email_delivery:
     delivery_method: :smtp
     smtp_settings:
       address: "smtp.yandex.ru"
       port: 25
       authentication: :plain
       domain: 'smtp.yandex.ru'
       user_name: 'robot@fablab61.ru'
       password: 'yarobot1'